import pandas as pd

# Define the columns for the grades Excel file
columns = [
    "name",
    "ron_min", "ron_max",
    "mon_min", "mon_max",
    "rvp_min", "rvp_max",
    "sulfur_ppm_min", "sulfur_ppm_max",
    "benzene_min", "benzene_max",
    "aromatics_min", "aromatics_max",
    "olefins_min", "olefins_max",
    "mtbe_min", "mtbe_max",
    "oxy_wt_min", "oxy_wt_max",
    "t10_min", "t10_max",
    "t50_min", "t50_max",
    "e70_min", "e70_max",
    "vli_min", "vli_max",
    "target_mass",
    "price_mode",
    "base_density_escalation",
    "ron_linear_min",
    "force_ethanol_enabled",
    "force_ethanol_mass_frac",
    "detergent_ppm",
    "corrosion_inhibitor_ppm",
    "ferrocene_ppm",
    "mmt_ppm",
]

# Example data for a few grades
rows = [
    [
        "Regular",
        91, None,
        81, None,
        None, 60,
        None, 10,
        None, 1,
        None, 35,
        None, 18,
        None, 15,
        None, 2.7,
        None, 70,
        None, 110,
        20, 48,
        None, 1200,
        1000,
        "as_is",
        None,
        None,
        False,
        0.0,
        None,
        None,
        None,
        None,
    ],
    [
        "Premium",
        95, None,
        85, None,
        None, 60,
        None, 10,
        None, 1,
        None, 35,
        None, 18,
        None, 15,
        None, 2.7,
        None, 70,
        None, 110,
        20, 48,
        None, 1200,
        1000,
        "as_is",
        None,
        None,
        False,
        0.0,
        None,
        None,
        5,
        2,
    ],
    [
        "E5_Regular",
        91, None,
        81, None,
        None, 60,
        None, 10,
        None, 1,
        None, 35,
        None, 18,
        None, 15,
        None, 2.7,
        None, 70,
        None, 110,
        20, 48,
        None, 1200,
        1000,
        "as_is",
        None,
        90.5,
        True,
        0.05,
        50,
        10,
        0.5,
        0.2,
    ],
    [
        "Premium_ESC",
        95, None,
        85, None,
        None, 60,
        None, 10,
        None, 1,
        None, 35,
        None, 18,
        None, 15,
        None, 2.7,
        None, 70,
        None, 110,
        20, 48,
        None, 1200,
        1000,
        "escalated",
        755.0,
        None,
        False,
        0.0,
        30,
        5,
        1,
        0.5,
    ],
]

df = pd.DataFrame(rows, columns=columns)
df.to_excel("sample_grades_template.xlsx", index=False)
print("Sample grades Excel file 'sample_grades_template.xlsx' created with Ferrocene and MMT columns.") 